"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_1 = require("../middleware/auth");
const bookingController_1 = require("../controllers/bookingController");
const router = (0, express_1.Router)();
router.use(auth_1.authMiddleware);
router.post('/', (req, res, next) => (0, bookingController_1.createBooking)(req, res, next));
router.post('/:id/cancel', (req, res, next) => (0, bookingController_1.cancelBooking)(req, res, next));
router.get('/my', (req, res, next) => (0, bookingController_1.getMyBookings)(req, res, next));
router.get('/:id', (req, res, next) => (0, bookingController_1.getBookingDetails)(req, res, next));
router.get('/:id/pdf', (req, res, next) => (0, bookingController_1.getBookingPdf)(req, res, next));
exports.default = router;
