"use strict";
/**
 * OpenAPI / Swagger UI docs route.
 *
 * - GET /docs          → HTML Swagger UI
 * - GET /docs/openapi.json → raw OpenAPI spec as JSON
 *
 * The spec is hand-written and committed at docs/openapi.yaml. To regenerate
 * the JSON view at runtime we ship a minimal YAML→object loader. For now we
 * ship a static JSON companion file generated by `npm run docs:build`.
 *
 * If docs/openapi.json is absent, /docs still renders with an inline spec.
 */
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const path_1 = __importDefault(require("path"));
const fs_1 = __importDefault(require("fs"));
const router = (0, express_1.Router)();
const OPENAPI_JSON_PATH = path_1.default.resolve(process.cwd(), 'docs/openapi.json');
let cachedSpec = null;
function loadSpec() {
    if (cachedSpec)
        return cachedSpec;
    try {
        if (fs_1.default.existsSync(OPENAPI_JSON_PATH)) {
            const raw = fs_1.default.readFileSync(OPENAPI_JSON_PATH, 'utf8');
            cachedSpec = JSON.parse(raw);
            return cachedSpec;
        }
    }
    catch {
        // fall through
    }
    // Fallback minimal spec
    cachedSpec = {
        openapi: '3.0.0',
        info: {
            title: 'Event Booking Platform API',
            version: '1.0.0',
            description: 'OpenAPI spec not built. Run `npm run docs:build` to generate docs/openapi.json from docs/openapi.yaml.',
        },
        paths: {},
    };
    return cachedSpec;
}
const SWAGGER_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Event Booking API — Docs</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css" />
  <style>
    body { margin: 0; }
    .topbar { background: #1f2937; color: #fff; padding: 12px 24px; font-family: -apple-system, sans-serif; }
    .topbar h1 { margin: 0; font-size: 18px; font-weight: 600; }
    .topbar small { color: #9ca3af; font-size: 12px; }
  </style>
</head>
<body>
  <div class="topbar">
    <h1>Event Booking Platform — API Reference</h1>
    <small>Versioned at /api/v1 · Legacy at /api (deprecated)</small>
  </div>
  <div id="swagger-ui"></div>
  <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    window.onload = () => {
      window.ui = SwaggerUIBundle({
        url: '/docs/openapi.json',
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [SwaggerUIBundle.presets.apis],
      });
    };
  </script>
</body>
</html>
`;
router.get('/', (_req, res) => {
    res.type('html').send(SWAGGER_HTML);
});
router.get('/openapi.json', (_req, res) => {
    res.type('application/json').json(loadSpec());
});
router.get('/openapi.yaml', (_req, res) => {
    const ymlPath = path_1.default.resolve(process.cwd(), 'docs/openapi.yaml');
    if (fs_1.default.existsSync(ymlPath)) {
        res.type('application/yaml').send(fs_1.default.readFileSync(ymlPath, 'utf8'));
    }
    else {
        res.status(404).json({ error: 'openapi.yaml not found' });
    }
});
exports.default = router;
