"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const organizerOrganizationController_1 = require("../controllers/organizerOrganizationController");
const organizerAuth_1 = require("../middleware/organizerAuth");
const router = (0, express_1.Router)();
router.use(organizerAuth_1.organizerAuthMiddleware);
router.get('/me', organizerOrganizationController_1.getOwnOrganization);
router.get('/:id', organizerOrganizationController_1.getOrganization);
router.patch('/:id', organizerOrganizationController_1.updateOrganization);
router.patch('/:id/banking', organizerOrganizationController_1.updateBanking);
router.post('/:id/deactivate', organizerOrganizationController_1.deactivateOrganization);
router.post('/:id/reactivate', organizerOrganizationController_1.reactivateOrganization);
exports.default = router;
