"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const scanController_1 = require("../controllers/scanController");
const adminAuth_1 = require("../middleware/adminAuth");
const router = (0, express_1.Router)();
router.use(adminAuth_1.adminAuthMiddleware);
router.post('/verify', (req, res, next) => (0, scanController_1.verifyTicket)(req, res, next));
router.post('/mark', (req, res, next) => (0, scanController_1.markTicket)(req, res, next));
exports.default = router;
